### ISSUE TITLE
How to make typescript keywords work

### ISSUE THREAD

**Issue by petersondrew** [liamsheppard/voodoo-theme#3]
First off, thanks for this great theme, I'm really enjoying it!

The one issue I'm having is that keywords like import/export, and probably a few I haven't noticed yet, work in javascript but not typescript files. I'm perfectly willing to fix this myself, but I'm very much in the dark on how these themes work (and the documentation really hasn't helped much).
If you could point me in the right direction I'd be happy to fix it and submit a PR.

Thanks again!

**Comment by liamsheppard** [comment]
Hey mate, super happy to hear you're enjoying the theme. I'll try giving it a go but if you'd like to learn, it took me a bit of trial and error too. The documentation is pretty rubbish.

So if you take a look at the JSON that stores all the colours, you can see that it targets "classnames" in a similar way to how css would, this bit's super self-explanatory. All you need to know is how to find the classes, to do this, just open the command menu (`cmd+shift+p` I think) and type in "`TM Scopes`", there should be something there about showing tm scopes, enable that and you can click any code and see what scope is used to colour that syntax

**Comment by liamsheppard** [comment]
https://github.com/liamsheppard/voodoo-theme/pull/4 and https://github.com/liamsheppard/voodoo-theme/pull/5

(I made a huge mess of that, haven't touched the code in a while)

Feel free to PR if I've missed anything @petersondrew

**Comment by petersondrew** [comment]
Thank you so much! I wasn't expecting you to do the work yourself, thank you!

If I notice anything I will use your tip on how to show `TM Scopes` and give it a shot myself.
